name: agent check 


on:
  pull_request:
    branches:
    - master
# on:
#   push:
#     branches:
#     - master
#     - release/*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install inxi

#     - name: OS info
#       run: cat /etc/*relea*
        
#     - name: Check sudo
#       run: |
#         set -x
#         sudo whoami
#         sudo parted -l | grep /dev/sd -B1 -A2
        
    - name: process info
      run: |
        ps aux                  

#     - name: test docker 
#       run: |
#         set -x
#         docker ps
#         docker run hello-world
    
    - name: nework test
      run: |
        set -x
        curl ifconfig.co
        which python
        curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
        ifconfig
        ping -t 7 tut.by

    - name: Run a hardware info
      run: |
        set -x
        whoami
        echo "System: "`lsb_release -d --short` `uname -m`
        echo "Kernel: "`uname -r`"  DE: $XDG_CURRENT_DESKTOP   Session: $GDMSESSION" 
        echo "----------------------------------"                                    
        echo "Processor: "`cat /proc/cpuinfo | grep "model name" -m1 | cut -c14-`    
        echo "Memory (Gb): "`free | grep Mem | awk '{print int($2/10485.76)/100}'`   
        echo "Video: "`lspci -k | egrep 'VGA|3D' -A2`                                
        echo "----------------------------------"
        df -hT
        free -mh
        inxi
        inxi -M
        sensors
        cpuid
