name: SSH check

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         key: ${{ secrets.KEY }} 
#         port: ${{ secrets.PORT }}
#         script: whoami

    - name: run ci-cd on stag
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.KEY }}
        HOST: ${{ secrets.HOST }}
        USER: root
      with:
#         args: cat /etc/*relea*
        args: uptime
